### ISSUE TITLE
CA: Committees, problem of multiple committees in one action

### ISSUE THREAD

**Issue by mhedblom** [openstates/openstates#1263]
California sometimes has actions descriptions that appear to assign a bill to multiple committees at the same time. **In fact, they are always only assigned to one at a time**. Here is an example of an action description:
```
Referred to Standing Committee on Education and Standing Committee on Human Services
```
OpenStates collects this information and publishes this information as a “related_entity”, like this:
```
  "related_entities":[
            {
               "type":"committee",
               "name":"Standing Committee on Education",
               "id":"CAC000738"
            },
            {
               "type":"committee",
               "name":"Standing Committee on Human Services",
               "id":"CAC000694"
            }
```
The information published by Calif. actually includes the necessary information, and it too is collected by OpenStates:
```
 "+actor_info":{
            "details":"Senate (Committee CS44)",
            "committee_code":"CS44"
         },
```
California publishes a look-up table (LOCATION_CODE_TBL.dat) that maps the “committee_code” to name. The CS44 code maps to the Education committee
```
`20152016` `CS44` `Sen Education` `Education` 
```
Interestingly, when I look at /openstates/ca/**bills.py**, I see these codes are hard-coded, but I don't see them being mapped or used.

We need to know which committee actually got the assignment (so we can look up the members by the OpenStates committee 'id'. Is there a way to include in the bill details or committee search, a way to map the committe_code to a committee ‘id’ so we can determine the committee members?

**Comment by jamesturk** [comment]
Thanks for this report, I'm a bit confused- that action description doesn't mean that it is being assigned to both committees?

As for the rest- we do pass along the +actor_info field for people that need raw info from the state that we don't directly support in OpenStates' code.  This may have to remain one of those cases.

Because we have to go elsewhere for the committee details we don't have a programmatic mapping of the original IDs to the committees we collect.  Within your own code could you map CA committee IDs to ours though?

**Comment by mhedblom** [comment]
The action description implies it is being assigned to multiple committees (sometimes even three), but in reality, a bill is only ever in one committee at a time, as identified by the committee_code.

My code doesn't have a mapping of committee_code to OpenStates committee ID.  My suggestion is that the Calif code being included in the committee API, AND, use the lookup table provided by California to map codes to name. Instead of hard coding the names and abbreviations in bills.py.

**Comment by jamesturk** [comment]
I think what we can do here is try to name match CA committees from the Committee scraper, however, since we have to use a different source to get a complete set of Comm. data I'm not sure what % will match.

Roughly (for future reference):

* Load CA LOCATION_CODE_TBL
* Pull Name->Code mapping by querying DB
* Within Comm Scraper check if name is in Name->Code mapping and assign to +committee_code
