### ISSUE TITLE
Return boundary IDs in state-level results

### ISSUE THREAD

**Issue by eropple** [openstates/openstates#1264]
When I call `/legislators/?state=ma` (or any other state), I don't receive a `boundary_id`field. I do with a geographic lookup. I can build an OCD identifier synthetically, but it's pretty gross to do so. Might be nice to just have it dumped via the API.

**Comment by eropple** [comment]
(Turns out I can't really build an OCD identifier synthetically for dear ol' Massachusetts. Suggestions very gratefully welcomed.)

**Comment by jamesturk** [comment]
Hi @eropple- just so we're clear, what're you trying to do with the boundary IDs?

(And yeah, MA districts are crazy enough that there isn't a great way to build them programatically.)

**Comment by eropple** [comment]
My object model is similar in general shape to the Google Civic Data "divisions have many offices which have many officials" setup. But Google's data is...let's be real...gross for state-level officials. So I'm currently pulling better data out of OpenStates (and similar U.S. congressional/senatorial data from Propublica/the Sunlight Labs API on that side). I'm building (or ensuring the existence of) office objects from the legislators that I'm pulling from other sources, and those are all foreign keyed to a division. Which creates the situation I've got here. 

I did manage to build them programmatically for MA, so my current problem isn't acute, but it's very duct-tapey.

**Comment by jamesturk** [comment]
We're going to be revisiting the API in the near future and I think this issue will be resolved then.  Marking as deferred for now (not because it isn't important, but because we're prioritizing data quality issues for the time being)

**Comment by halffullheart** [comment]
Open Civic Data has mappings from OCD divisions to Open States districts. [Here is the one for MA](https://github.com/opencivicdata/ocd-division-ids/blob/master/identifiers/country-us/openstates/state-ma-openstates.csv).

I would also be interested in seeing OCD divisions returned by Open States. I’m also using Google Civic Data to look up divisions by address, since they provide divisions for US, state, and local bodies all at once. But since their data isn’t great, I’m using other data sources to fill in and ideally OCD division IDs would be a great way to glue everything together.

**Comment by jamesturk** [comment]
going to close this issue  as it will be part of planning in openstates/meta#21
