### ISSUE TITLE
Consider adding a nickname or common_name field for state legislators

### ISSUE THREAD

**Issue by samtregar** [openstates/openstates#1275]
There are many reps who aren't commonly known by their legal names.  For example, MDL000277 is listed as C. William Frick but he goes by Bill (as seen in his email address, bill.frick@house.state.md.us).  There are many examples like this that are currently getting into first_name data but would be more useful if they were separated out.

**Comment by mileswwatkins** [comment]
So, one of the next steps on our roadmap is switching from Billy to OCD backend. This will mean (in keeping with [the OCD/Popoplo spec](http://www.popoloproject.com/specs/person.html)) that we no longer split names into first and last, and rather have one monolithic main name. In many scrapers, we're already eschewing splitting names into first and last.

This OCD spec choice was partly made since not all cultures have given and surnames; this affected OS occasionally regarding state legislatures who have Native-American-style names.

However, if the legislature _does_ list nicknames or short names, those can be stashed in the `alternate names` field in OCD, so worth keeping an eye out going forward.

Let us know if you have any further questions in this area, though!

**Comment by samtregar** [comment]
What's the timeline on the move to the OCD backend?  Thanks!

**Comment by mileswwatkins** [comment]
We're close to having all 52 scraper sets back up; @jamesturk and I will be putting out a [blog post](https://blog.openstates.org/) soon afterwards with next-steps. It'll be in the coming months (rather than the coming weeks, or next year).
