### ISSUE TITLE
TX: Missing email addresses for all legislators

### ISSUE THREAD

**Issue by richardm** [openstates/openstates#1292]
The email field is null for everyone. This information doesn't appear to be present on the pages being scraped. In Texas, the email addresses are simply firstname.lastname@house.state.tx.us or firstname.lastname@senate.state.tx.us.

I'm not sure if there is a place to scrape them from the Texas Legislature website or if it's easier just to hard code them, but the Texas Tribune does maintain an elected officials directory with the email addresses:
https://www.texastribune.org/directory/#texas_house_tab
https://www.texastribune.org/directory/#texas_senate_tab

**Comment by grgcombs** [comment]
I think this is because there isn't an *official* place to scrape them.  The legislative reference library has (or had) social media info for legislators, but no one there really advertises the email addresses or the formula for deriving them.

**Comment by jonConerly** [comment]
The [official lower chamber](http://www.house.state.tx.us/resources/frequently-asked-questions/#email_rep) way to email according to the State website is to use the email web form on each of the legislator's page.  The link to the email form can be scraped or predicted(sample link: http://www.house.state.tx.us/members/member-page/email/?district=104&session=85) if we wanted to provide a direct link to it instead of an actual email address.  The FAQ page also mentions that not all members use email for what it is worth.

Similarly the [official upper chamber](http://www.senate.texas.gov/FAQ.php) way to email is to use the web form by clicking the email button on the Senator's page, however some senators do not accept email and will not have the button to access the email form.  The link to the email page cannot be scraped or predicted.  The reason why it cannot be scraped is due to the auth parameter of the URL that is acting as an access token and as the only method in the URL that will take you to the right location:
http://www.senate.texas.gov/memberform.php?auth=29tBtyNR%2BqhEbbOo1JR%2FnRUnLlOFLHcJVkgvA%2BEkJCUbbjp8Onw6UW0uCzIGd3frrZeyzb62VSViP4Tzr1zJ2rYnxsGACCU%3D&lang=en

Based just having a browser tab open for 5-10 minutes on a senator's page, the auth token of the email form expired and it would only give a 302 redirect back to the senator's main page.  Not sure if it is actually time based tokens or not, but something can invalidate them and they will change between full page reloads.

**Comment by jamesturk** [comment]
I think given the complexities of the webforms we should consider manual collection here (not necessarily precluding also collecting webforms).  Since TX Tribune is doing it we should see if we can get them to give us their list, or collect it using their site.

**Comment by richardm** [comment]
I spoke with a district director for a state rep here in Texas. I was told that the web form has the advantage of logging the user contact information into the legislature's CMS system where they can capture the name, address, email, etc. to use for correspondence. Other than that, every elected rep and senator can receive email at firstname.lastname@house.state.tx.us.

**Comment by jamesturk** [comment]
this will now be handled via https://github.com/openstates/people, if there's an appetite for this please open an issue there as data can now be added manually that wasn't available in the scrape
