### ISSUE TITLE
Legislator documentation is out of date / missing fields

### ISSUE THREAD

**Issue by richardm** [openstates/openstates#1293]
I noticed that a few available fields are not listed here:
http://docs.openstates.org/api/legislators.html

At minimum these are missing from the list but are present in the sample data dump:
level, transparencydata_id, votesmart_id

**Comment by mileswwatkins** [comment]
There are many "optional fields" that are included somewhere, but aren't part of the core Open States information about a legislator. For example, there are extra IDs included for some legislators that link them to campaign finance or other data, much of it related to deprecated Sunlight Foundation projects and not maintained anymore.

Given this, and since we're switching to an improved data spec (Open Civic Data) in the coming months, I'm going to close this ticket. But you're right that we should improve the documentation of these additional fields if and when we add them in OCD.
