### ISSUE TITLE
KS Committee Information Incorrect

### ISSUE THREAD

**Issue by Wizofgoz** [openstates/openstates#1316]
Related to #1260 
The members, in particular seem to be off.

Here's an example:
[OpenStates](https://openstates.org/api/v1//committees/KSC000025/?state=ks&active=true&apikey=xxxxxx)
vs
[KS Website](http://kslegislature.org/li/b2017_18/committees/ctte_s_assess_tax_1/)
or
[KS API](http://www.kslegislature.org/li/api/v7/rev-1/ctte/ctte_s_assess_tax_1/)

Also, the example in #1260 seems to reflect the same

**Comment by jamesturk** [comment]
cc @erinspace

**Comment by mshenfield** [comment]
The Open States API has out of date committee members.

Scraping locally, received warnings like the following:

```
02:02:47 WARNING billy: error fetching committee http://www.kslegislature.org/li/api/v7/rev-1/ctte/ctte_sub_public_safety_subcommittee_ways_and_means_1/
```

These warnings may have gone unnoticed, allowing the scrape to finish without updating the data for some committees.

Copying the link quickly after it was printed to see the response in the browser, I got a [429](https://httpstatuses.com/429) error code and a message instructing me to limit requests to once every 3-5 seconds.

<img width="1438" alt="KS API 429" src="https://cloud.githubusercontent.com/assets/4812055/22722795/02833234-ed7f-11e6-8a0d-0b01985118d4.png">

Adding a rate limit to 5 seconds (12 RPM) did not fully fix the issue. Instead of the logged warning above, the scrape crashed after a random number of committees with this stack trace:

```
Traceback (most recent call last):
File "/usr/local/bin/billy-update", line 9, in <module>
  load_entry_point('billy==1.9.0', 'console_scripts', 'billy-update')()
File "/opt/openstates/billy/billy/bin/update.py", line 380, in main
  run_record += _run_scraper(stype, args, metadata)
File "/opt/openstates/billy/billy/bin/update.py", line 104, in _run_scraper
  scraper.scrape(chamber, time)
File "/srv/openstates-web/openstates/ks/committees.py", line 20, in scrape
  self.scrape_current(chamber, term)
File "/srv/openstates-web/openstates/ks/committees.py", line 44, in scrape_current
  detail_json = self.get(com_url).text
File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 469, in get
  return self.request('GET', url, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/scrapelib/__init__.py", line 270, in request
  **kwargs)
File "/usr/local/lib/python2.7/dist-packages/scrapelib/cache.py", line 66, in request
  resp = super(CachingSession, self).request(method, url, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/scrapelib/__init__.py", line 92, in request
  return super(ThrottledSession, self).request(method, url, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/scrapelib/__init__.py", line 177, in request
  raise exception_raised
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

Limiting it further to one request every 6 seconds (10 RPM) seems to solve the issue and run a complete scrape without any exceptions.

Here is a copy of the up to date committee entry for the example at the top of the issue:

```
{"_type": "committee", "committee": "Assessment and Taxation", "chamber": "upper", "sources": [{"url": "http://www.kslegislature.org/li/api/v7/rev-1/ctte/ctte_s_assess_tax_1/"}], "state": "ks", "subcommittee": null, "members": [{"role": "chairman", "name": "Caryn Tyson"}, {"role": "vice-chairman", "name": "Dan Kerschen"}, {"role": "ranking member", "name": "Tom Holland"}, {"role": "member", "name": "Larry Alley"}, {"role": "member", "name": "Jim Denning"}, {"role": "member", "name": "Marci Francisco"}, {"role": "member", "name": "Dan Goddard"}, {"role": "member", "name": "Julia Lynn"}, {"role": "member", "name": "Mike Petersen"}]}
```

**Comment by jamesturk** [comment]
lowered RPM in production, will look over this tomorrow to see if comms are updated
