### ISSUE TITLE
Document state api keys

### ISSUE THREAD

**Issue by jmcarp** [openstates/openstates#1323]
As an open source contributor, I want to know which states require api keys to run scrapers, and where to get them. As far as I can tell, it's just NH and NY, and keys come from http://docs.api.iga.in.gov/introduction.html and http://legislation.nysenate.gov, respectively. Is that right?

**Comment by mileswwatkins** [comment]
Good point about documenting these, and AFAIR those two states are the only ones that require keys. Would it be best to include these in state-directory READMEs? Or do you think a different way would be easier for the average dev?

Related, I saw your message on the Slack about sharing the Indiana API key, but didn't respond because I'm torn. We obviously do have an IN key that's used in production, but since IN keys are difficult to acquire, I'm mostly in favor of minimizing the use of it in testing/developing in case we wrote some unfortunate loop or the like that got IN admins mad at us. Instead, we should get some sorta secondary, "staging"/"testing" IN API key that's shared among trusted developers.

@rshorey, on that note, any luck getting a backup IN key?

**Comment by mileswwatkins** [comment]
(Also, I think NY keys are pretty much automatically distributed.)

**Comment by rshorey** [comment]
I only know about Indiana, so my response is limited to that. I believe we cannot share the IN API key according to whatever document was agreed to in order to get it.

I have not had any luck getting anyone in Indiana to respond to any question I have asked them. Ever. I will try again. If I am ever successful at getting in touch, I will press them for instructions about how to get one of these keys and post them here.

**Comment by jonConerly** [comment]
If you are emailing the address in the documentation, it might not be the best person anymore, some research into the API and inherently the LSA makes me think maybe the documentation just has not been updated and promotions/title changes have now made that contact a less than optimal person to give out API keys(CSOs generally don't do that kind of thing). 

The API does seem to be more public than before or at least to some. They've had more than one [hackathons](http://www.indychamber.com/files/3114/5652/9187/LSAchallenge.pdf) put on by a local [organization](http://openindybrigade.com/2016/02/08/indy-civic-techs-tipping-point/) dedicated to open data.  Contacting the openindybrigade might give better results than the documented contact, they link [here](https://www.data.gov/developers/blog/primer-machine-readability-online-documents-and-data) on the their site and even mentioned and linked Sunlight in their [Open Data Review](http://openindybrigade.com/projects/open-data-review/).

**Comment by rshorey** [comment]
cool, thanks for the heads up. I've contacted nearly every official help address/phone number on the state website, but I'll definitely check in with brigade and see if they have any tips and/or can provide a key.

**Comment by jmcarp** [comment]
From indy brigade slack:

<img width="590" alt="screen shot 2017-02-03 at 10 00 51 pm" src="https://cloud.githubusercontent.com/assets/1633460/22615148/6b7aa018-ea5c-11e6-9ae0-4d6d64424972.png">

**Comment by rshorey** [comment]
Thanks, I made some phone calls today and got contact info of the person who can give me a key but stupidly left it on a piece of paper in my office. I won't be back till Thursday but will keep working on that then.

**Comment by jamesturk** [comment]
I think what we should do as a matter of policy:

* Maintain a second set of keys we can share w/ developers that is different from our production keys.
* In the README/updated contributing docs point people in the right direction to get their own, but we will also have a second set that we _can_ share if need be without jeopardizing our nightly scrape.

This also applies to things like NC's IP whitelist.

**Comment by jamesturk** [comment]
When we have a better sense of the best path to get an Indiana API key let's add it here: 

https://github.com/openstates/meta/wiki/State-API-Keys

**Comment by rshorey** [comment]
I acquired an Indiana API key and have added the contact info to do so to https://github.com/openstates/documentation//blob/master/policies/state-api-keys.rst

I'm going to close this issue, since we've got IN and NY documented there and I think that's it for states that require API keys.

**Comment by jmcarp** [comment]
Thanks!
