### ISSUE TITLE
TX: Committee list and membership is scraping from the old session's URL?

### ISSUE THREAD

**Issue by grgcombs** [openstates/openstates#1325]
State: TX

The committees and the committee membership pages are being scraped from URLs for the 84th session instead of URLs for the current 85th session.  At least this is what the committees.sources.url query parameters seem to indicate...

For each committee's membership, the scraper is currently looking at URLs like this (notice the LegSess parameter is **84R**, meaning 84th Regular Session):

    http://www.capitol.state.tx.us/Committees/MembershipCmte.aspx?LegSess=84R&CmteCode=C500

It should be scraping membership listings for the current/85th session using URLs like this (LegSess=85R):

    http://www.capitol.state.tx.us/Committees/MembershipCmte.aspx?LegSess=85R&CmteCode=C500

Note that at the time of this writing, the House still hasn't published any committee memberships -- those will probably come out sometime in the next month or so.  However, the Senate's committee memberships are updated and published.

**Comment by jonConerly** [comment]
Are you running this from the production scrapers or have local changes not in master by chance?  My local branch is pulling 85R for upper(works) and lower(exception):
18:38:50 DEBUG requests.packages.urllib3.connectionpool: "GET /Committees/MembershipCmte.aspx?LegSess=85R&CmteCode=C020 HTTP/1.1" 200 9581

Scraping the lower committee membership pages throws an AttributeError exception because the committee scraper does not check to see if the membership table exists before trying to read it and/or lxmlize.get_nodes does not check the validity of the object it receives before trying to use the xpath attribute.  I could see a local change being made to keep the scraper from crashing out on production, although this looks like more of a bug that the scraper can't handle a blank membership page.

If you aren't using a prod copy, I don't see how the version could be set to 84 in code.  The committees' list page is hard coded to:  http://www.capitol.state.tx.us/Committees/CommitteesMbrs.aspx?Chamber=H which defaults the to the 85th session; all the committee membership links are scraped from the page without any metadata substitution.

**Comment by grgcombs** [comment]
I wasn't running it myself, just seeing the issue in the results from the API at https://openstates.org/api/v1

**Comment by showerst** [comment]
@jonConerly just confirming your comment that the scraper is fine. 

@jamesturk how have you dealt with source urls changing in the past, did you just blow that URL away when you rescrape, or leave it and if the state page changes append the new one?

**Comment by jamesturk** [comment]
We haven't run TX comms in production yet because of outstanding issues.  It looks like TX upper is working, but we'll  need a fix here for TX lower.

& to answer your question @showerst- We've just let old source URLs disappear in the past.
