### ISSUE TITLE
CA: add long bill titles

### ISSUE THREAD

**Issue by pqnelson** [openstates/openstates#1380]
CA bills do not have correct titles.

For example, [AB 817 (2015-2016)](https://openstates.org/ca/bills/20152016/AB817/) is entitled "An act to amend Section 22584 of the Business and Professions Code, relating to privacy" according to the CA's [bill page](http://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=201520160AB817) but Openstates lists it as "Privacy: students."

Clearly the Openstates title "Privacy: students" is incorrect. This is the bill's keywords/subjects, not its title.

**Comment by showerst** [comment]
I took a look at the [SQL files](http://downloads.leginfo.legislature.ca.gov/) we use, and the title doesn't seem to be a field there. It looks like maybe we can extract it by parsing the bill_version_tbl version XML, although some of them get [pretty long.](http://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=201720180AB1).

The state itself actually lists search results the same way openstates does, by the subject. I wonder if they do that because of the length of the alternate titles?

**Comment by jamesturk** [comment]
Yeah, I think this is more on California- on this page for instance https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=201720180AB1 the title element on the page seems right, and matches what we have.

There's a long title which is a pretty impractical thing, in a few states that's all we have so we use them, but they're essentially useless for the average citizen so I'd favor the 2-3 word title for display purposes.

We can capture the longer title too, as an additional title (something Billy and Pupa both support) but I'm going to say that we'll do the same thing CA does and favor the short title.

**Comment by hiteshgarg14** [comment]
Looking for the title on this [Link](https://leginfo.legislature.ca.gov/faces/billStatusClient.xhtml?bill_id=201720180AB1), It is very long and we have many cases like this. 

I am working on this, To replace `Topic` section (which is used to reference the title of the bill ) with real `Title` section.

**Comment by jamesturk** [comment]
@schneidy for when you're back

**Comment by jamesturk** [comment]
looks like CA currently takes ~50 minutes, @schneidy can you let me know how long a run takes (without --fast) with this. new code from #3224

**Comment by jamesturk** [comment]
reverted this commit in f99a320cefeb40221ede9dc9d1988b25b9eaaf36
