### ISSUE TITLE
ND: Bill numbers are being added instead of vote names

### ISSUE THREAD

**Issue by mshenfield** [openstates/openstates#1516]
The [ND vote scraper](http://github.com/openstates/openstates/blob/63ede9983ff6b8b26aeb2c29ad715f017c940746/openstates/nd/votes.py#L219) is saving bill numbers instead of the names of voters:

Some examples:
SB 2062, SB 2063, SB 2064, SB 2065, SB 2066, SB 2067

This is causing the vote to come back with a null leg_id, since the name cannot be matched back to a known legislator.

**Comment by NixGD** [comment]
This is because the scraper assumes that the resulting verdict will all fit into one line, for example, "Engrossed SB 2201 passed".  If we look at[ the daily report](http://www.legis.nd.gov/assembly/65-2017/journals/sr-dailyjnl-17.pdf#page=3) for the day there was a large batch of bills voted on all at once, and thus this summary spilled over into multiple lines.  Not sure what the best fix for this is, but will try to get something working in the next couple days.

**Comment by NixGD** [comment]
@mileswwatkins @jamesturk

The particular vote took place because the executive branch introduced 24 appropriations bills into the house and senate.  Given the legislative’s preference for their own appropriations bills they were batch rejected the executive ones using a consent calendar.

The person I talked to on the ND legislators council said he didn't recall this ever having been done in the past, certainly not in the past couple of years.

I think we have a couple options:
- Ignore the problem, and have the vote continue to only be identified with [SB 2085](https://openstates.org/nd/votes/NDV00007827/)
- Treat it as is 24 separate votes, each on one bill.
- Implement a many to one relationship with votes to bills.

**Comment by mileswwatkins** [comment]
This is tough!

**Ignore the problem**: Well, we know about it, so let's do something about it. We can fall back to this in _absolute worst_ case.
**Implement many to one**: We're too close to leaving Billy to do an implementation change like this on that end. @jamesturk, would OCD allow a 1:m between `Bill` and `VoteEvent`?
**Treat it as separate votes**: Might be the easiest option here, but I'm not sure how implementation would go, regarding assigning the vote to Billy `Vote` and `Bill` objects. Might have to fudge the "name" of the vote?

**Comment by jamesturk** [comment]
Right now it is 1:1 in OCD.  My vote is for treating it as separate votes if this is indeed a weird exceptional case.  I think you'd just have to create 1 VoteEvent object per Bill, since bill is used as a differentiator of VoteEvent objects right now.

**Comment by mileswwatkins** [comment]
Alright, @NixGD, thanks for your gumshoe dedication. Can you modify the text parser to produce a discrete vote for each of the bills? Thanks!

**Comment by NixGD** [comment]
Sounds like a plan!  This week has been a bit busy but I'll certainly fix it in a day or two.  Thanks for all your help!
