### ISSUE TITLE
KY: needs new vote scraper

### ISSUE THREAD

**Issue by jamesturk** [openstates/openstates#1542]
State: KY

KY's vote scraper is a no-op

**Comment by In-vincible** [comment]
@jamesturk is this ready to go issue?

**Comment by In-vincible** [comment]
I have started working at this one.

**Comment by In-vincible** [comment]
@jamesturk Do we want to rewrite the scraper for votes, and link from where we want to scrape? I think I will need few clear directions than I will be good to go :)

**Comment by In-vincible** [comment]
I did came through this link where I was able to find data for votes, for example : https://legiscan.com/KY/supplement/HB540/id/56487/Kentucky-2017-HB540-Vote_History_for_HB540.pdf is this source reliable enough? I just need the right source after that I can continue by myself.

**Comment by jamesturk** [comment]
We'll need to find a source on KY legislature, legiscan isn't a primary
source.  We can port to pupa without this though because we don't have a
working KY vote scraper today anyway.  I'd check existing KY work though, I
believe there's already a branch

**Comment by pqnelson** [comment]
For what it's worth, the legiscan data _is_ obtainable from the official Kentucky state legislature (e.g., for HB540 which In-vincible linked to, you can go to [the official page for the bill](http://www.lrc.ky.gov/record/17RS/HB540.htm) and under the [vote history link](http://www.lrc.ky.gov/record/17RS/HB540/vote_history.pdf) you find the pdf in question).

The problem is the KY Senate doesn't have a friendly PDF version for the votes (c.f., the vote history for [SB219](http://www.lrc.ky.gov/record/17RS/SB219/vote_history.pdf)).
