### ISSUE TITLE
[most states] Current sessions are missing start, end dates; proposed fix

### ISSUE THREAD

**Issue by estaub** [openstates/openstates#1671]
The current session for most states is missing start_date and end_date.  So are many earlier sessions

Because of this, AFAICT, the only simple way to find the current session for a state, is to sort lexicographically, which is defective when e.g. going from session 99 to 100.

I'd like to get the current session dates filled in for today's sprint.  
Is src/billy_metadata the source for these?

I plan to use ballotpedia where they have data, or the state where ballotpedia has none.  I intend to fill in the end date with the projected date; if a session runs long it should be fixed.

**Comment by mileswwatkins** [comment]
> the only simple way to find the current session for a state

Sessions are _always_ listed in temporal order in the metadata/jurisdiction info. Furthermore, within a Pupa scraper you can use `self.current_session()` to get the ID string of the most recent session.

That said, adding these start and end dates wouldn't hurt at all, and `start_date` and `end_date` are definitely [supported on Pupa](https://github.com/opencivicdata/pupa/blob/master/pupa/scrape/schemas/jurisdiction.py#L16-L17). IIRC, @showerst was also pushing for having better date info included.

Also, regarding sourcing data: I'd go _first_ to the state legislature's official website, and _then_ gather/cross-check from Ballotpedia. Totally get that it's easier to grab quickly from Ballotpedia, but it _is_ a secondary source rather than a primary one.

**Comment by jamesturk** [comment]
You actually *can* get this via the API, but dates are still welcome.

metadata['terms'][-1]['sessions'][-1] should be right, that's what we use to run the scraper just for the latest session.  if it ever isn't the latest that's a bug (special sessions can sometimes complicate this, but you could add logic to account for this)
