### ISSUE TITLE
GA: Not getting committee assignments

### ISSUE THREAD

**Issue by nitrag** [openstates/openstates#2070]
State: GA

[https://openstates.org/api/v1/committees/?state=ga&apikey=KEY&fields=first_name,last_name,leg_id,committee,chamber,subcommittee,members](https://openstates.org/api/v1/committees/?state=ga&apikey=KEY&fields=first_name,last_name,leg_id,committee,chamber,subcommittee,members)

The `members` array field is empty. Works for SC.

**Comment by nitrag** [comment]
```bash
$ docker-compose run --rm scrape ga committees
Starting openstates_database_1 ... done
no pupa_settings on path, using defaults
21:55:09 CRITICAL pupa: no such scraper: module=ga scraper=committees
```

**Comment by nitrag** [comment]
Okay it's supposed to be `committee`. I just ran it manually and it is scraping fine. Why is it not getting saved into your database?

Even blank on your website:
https://openstates.org/ga/legislators/GAL000001/john-albers/#committees

Sidebar because I'm curious:
How come some states are `committee` (GA, MS) and other states are `committees` (NY).  Also, why do some states have committee commented out? Where does this `scraper` dictionary actually get called from/used?

```
scrapers = {
        "people": MSLegislatorScraper,
        "committee": MSCommitteeScraper,
        "bills": MSBillScraper
    }
```

**Comment by nitrag** [comment]
I'm assuming you guys have a map of UUID's (eg. to GAL000001)?
```bash
$ cat _data/ga/post_78521f3e-f689-11e7-8d15-0242ac110002.json

{"contact_details": [], "role": "Senator", "label": "2", "organization_id": "7851cc5a-f689-11e7-8d15-0242ac110002", "division_id": "ocd-division/country:us/state:ga/sldl:2", "links": [], "_id": "78521f3e-f689-11e7-8d15-0242ac110002", "extras": {}, "end_date": "", "start_date": ""}
```

**Comment by jamesturk** [comment]
They should all be committee actually but it wasn't checked carefully I
guess, in practice the name of that key only matters if/when someone tries
to call them directly so that is easy to miss.

A lot of comm scrapers are disabled currently, we're running a bunch
tonight actually to see what is working post-session switchover.  It may
resolve this issue, we'll take a look tomorrow

The dictionary is used by pupa (the framework used for running the
scrapers) when processing its command line arguments.

(oh and the GUIDs are mapped at DB import time)

**Comment by nitrag** [comment]
It's flowing now with results. There are several members who aren't mapping to a `leg_id`:

Mary Oliver
James Epps
Pedro Marin
Mable Thomas
Freddie Sims
Lawrence Walker III

**Comment by jamesturk** [comment]
fixed & will now be handled in openstates/people from now on
