### ISSUE TITLE
OH: `get_session_list` cannot "see" current session

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/openstates#2159]
Ohio's `get_session_list` appears to have the current session _manually appended_. Not to mention, it hasn't been updated in a year. This should be fixed, to automatically "guess" the current session instead.

https://github.com/openstates/openstates/blob/master/openstates/oh/__init__.py#L91-L92

**Comment by shreyakupadhyay** [comment]
I would like to work on this issue.

**Comment by shreyakupadhyay** [comment]
Do we just want the current session because the code(https://github.com/openstates/openstates/blob/master/openstates/oh/__init__.py#L88) just scrapes the sessions till 130. And after that two more sessions(131, 132) are there. If we are extracting only 132 which is the current session, should we leave 131 or should we scrape both. There is one more way if the current session is 132, obviously 131 would also be there. For this we can append sessions which are there in between the current session and session 130.

**Comment by mileswwatkins** [comment]
@shreyakupadhyay, basically we need to find a way to identify all of the sessions that the legislature knows about. Looks like http://archives.legislature.state.oh.us/ will _only ever_ know about sessions from 1997–2014. You can find the more recent (ie, post-2014) list of General Assemblies on https://www.legislature.ohio.gov/legislation/search-legislation?2.

The main purpose of `get_session_list` is to throw an error when `legislative_sessions` is missing a new session. So, maybe the solution is to switch from the former source to the latter source?

**Comment by mileswwatkins** [comment]
(This is because we don't _need_ to see all the older sessions, mainly just know about any new sessions that come up.)

**Comment by shreyakupadhyay** [comment]
Yeah, I have used https://www.legislature.ohio.gov/legislation/search-legislation for getting the current session as http://archives.legislature.state.oh.us/ this was till 2014. As you mentioned we just want the latest session, so I will remove the former source and just use the latter source.
